version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
  mysql:
    image: mysql
    ports:
      - "3333:3306"
  backend:
    image: node
    ports:
      - "8000:8000"
  mongodb:
    image: mongodb
    ports:
      - "3888:3888"
